[package]
name = "optpy"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.0.19", features = ["derive"] }
optpy-parser = { path = "./optpy-parser" }
optpy-resolver = { path = "./optpy-resolver" }
optpy-generator = { path = "./optpy-generator" }

[workspace]
members = [
    "optpy-parser",
    "optpy-resolver",
    "optpy-test-helper",
    "optpy-std",
    "optpy-generator",
]
