[package]
name = "optpy-resolver"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
optpy-parser = { path = "../optpy-parser" }

[dev-dependencies]
optpy-test-helper = { path = "../optpy-test-helper" }
