[package]
name = "optpy-generator"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"

optpy-parser = { path = "../optpy-parser" }

[dev-dependencies]
optpy-resolver = { path = "../optpy-resolver" }
