[package]
name = "optpy-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.65", features = ["backtrace"] }
proc-macro2 = "1.0.47"
quote = "1.0.21"
rustpython-parser = "0.1.2"
